version: '3.8'

services:

  web:
    build:
      context: .

      dockerfile: docker/php/Dockerfile
    container_name: hacer1u1_web
    ports:
      - "80:80" 
    volumes:
      - .:/var/www/html
    depends_on:
      - db

 
  db:
    image: mysql:5.7
    container_name: hacer1u1_db
    environment:
      
      MYSQL_ROOT_PASSWORD: molotov
      MYSQL_DATABASE: hacer1u1_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: molotov
    volumes:
      - db_data:/var/lib/mysql
    
    
      - ./protect.sql:/docker-entrypoint-initdb.d/protect.sql
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hacer1u1_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: molotov
    ports:
      - "8080:80" 
    depends_on:
      - db


volumes:
  db_data:
